apiVersion: v2
name: k8s-infra
description: Helm chart for collecting Kubernetes metrics, logs and events with OpenTelemetry
type: application
version: 1.0.0
appVersion: "0.139.0"
keywords:
  - OpenTelemetry
  - otel
  - kubernetes
  - observability
  - monitoring
  - logs
  - metrics
sources:
  - https://github.com/open-telemetry/opentelemetry-collector-contrib
maintainers:
  - name: prashant-shahi
    url: https://github.com/prashant-shahi
