apiVersion: v2
name: otel-gateway
description: A Helm chart for deploying an OpenTelemetry gateway collector
type: application
version: 0.1.0
appVersion: "0.139.0"
keywords:
  - OpenTelemetry
  - otel
  - gateway
  - observability
  - monitoring
sources:
  - https://github.com/open-telemetry/opentelemetry-collector
  - https://github.com/open-telemetry/opentelemetry-collector-contrib
maintainers:
  - name: prashant-shahi
    url: https://github.com/prashant-shahi
